stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
  artifacts:
    name: images
    expose_as: images
    expire_in: 3 days
    paths:
      - images
  cache:
    paths:
      - layers

meta-odroid-image:
  extends: .build
  script:
  - kas build kas-meta-odroid-image.yml
  - |
    #if [[ -n "$B2_KEY_ID" ]]; then
    #    echo "Backing up $CI_DEFAULT_BRANCH"
    #    rclone config create b2 b2 account $B2_KEY_ID key $B2_APP_KEY > /dev/null
    #    rclone copy --ignore-existing build/sstate-cache/ b2:ak-oebuilds/sstate/$CI_DEFAULT_BRANCH/
    #    rclone copy --ignore-existing build/tmp/deploy/sources/mirror/ b2:ak-oebuilds/mirror/$CI_DEFAULT_BRANCH/
    #fi
