stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
  cache:
    paths:
      - layers

odroid-xu3-lite:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-c1:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-c2:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-h2:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-xu4:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-hc1:
  extends: .build
  script:
  - kas build --target core-image-base  kas/$CI_JOB_NAME.yml

odroid-xu3:
  extends: .build
  script:
   - kas build --target security-build-image kas/$CI_JOB_NAME.yml

odroid-xu3-lite-x11:
  extends: .build
  script:
  - kas build --target odroid-x11-image kas/$CI_JOB_NAME.yml

odroid-h2-x11:
  extends: .build
  script:
  - kas build --target odroid-x11-image kas/$CI_JOB_NAME.yml

odroid-xu4-x11:
  extends: .build
  script:
  - kas build --target odroid-x11-image kas/$CI_JOB_NAME.yml


cleanup:
  stage: .post
  before_script:
  - wget -q 'http://git.yoctoproject.org/cgit/cgit.cgi/poky/plain/scripts/sstate-cache-management.sh'
  - chmod +x  sstate-cache-management.sh

  script:
  - ./scripts/ci-cleanup.sh
