stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
  artifacts:
    name: images
    expose_as: images
    expire_in: 3 days
    paths:
      - images
  cache:
    paths:
      - layers

meta-odroid-image:
  extends: .build
  script:
  - kas build kas-meta-odroid-image.yml
