dist: xenial
sudo: required
language: shell
compiler:
env:

before_install:

install:
- sudo apt-get update -qq
- sudo apt-get remove -y -qq oss4-dev
- sudo apt-get install -y -qq gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python-git
script:
- mkdir -p ~/bin
- PATH=~/bin:$PATH
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- mkdir -p odroid-oe
- git config --global color.ui true
- repo init -u git://github.com/akuster/meta-odroid  -b master -m tools/manifests/odroid-oe.xml
- repo sync
- repo start work --all
- . ./meta-odroid/setup.sh
- bitbake core-image-minimal

after_success:
